#!/usr/bin/zsh 

### Job Parameters 
#SBATCH --partition=c23g
#SBATCH --time=10:00:00         
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate dev

python /hpcwork/nq011071/earthnetThesis/checkGPU.py

python /hpcwork/nq011071/earthnetThesis/swinUnet/trainVideoSwinUnetWeatherAE.py --config /hpcwork/nq011071/earthnetThesis/rwthHPCRuns/configWeatherDataAE.yml 
#--resumeTraining --resumeCheckpoint /home/nikoskot/earthnetThesis/experiments/weatherDataAE/weatherDataAE_26-09-2024_04-51-29/checkpointLast.pth

# python /home/nikoskot/earthnetThesis/swinUnet/testVideoSwinUnet.py --trainingFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_20-09-2024_18-43-53 --testSplit iid_test_split --checkpoint checkpoint_22-09-2024_02-53-50.pth

# python /home/nikoskot/earthnetThesis/swinUnet/ensScoreCalculation.py --predictionsFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_20-09-2024_18-43-53/predictions/checkpoint_22-09-2024_02-53-50.pth/iid_test_split --targetsFolder /home/nikoskot/earthnetThesis/EarthnetDataset/iid_test_split/target --dataOutputFilePath /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_20-09-2024_18-43-53/checkpoint_22-09-2024_02-53-50data_output.json --scoreOutputFilePath /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_20-09-2024_18-43-53/checkpoint_22-09-2024_02-53-50score_output.json