#!/bin/bash
#SBATCH --partition=A100medium
#SBATCH --time=24:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16


python checkGPU.py

python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/configV1RedLR.yml

