#!/bin/bash
#SBATCH --partition=A100short
#SBATCH --time=8:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --dependency=afterany:120938

python checkGPU.py

python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/configV1CosAn.yml --resumeTraining --resumeCheckpoint /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_12-09-2024_18-13-06/checkpoint.pth


