#!/bin/bash
#SBATCH --partition=A100short
#SBATCH --time=8:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mail-type=ALL

#python checkGPU.py
#module load PyTorch/1.12.1-foss-2022a-CUDA-11.7.0
#python checkGPU.py
#source ~/.bashrc
#conda activate thesis
#module list
#module load PyTorch/1.12.1-foss-2022a-CUDA-11.7.0
#module list
python checkGPU.py
# python swinUnet/videoSwinUnetMMAction.py

# python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/config.yml
# python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/config1.yml
# python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/config2.yml
# python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/config3.yml
# python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/config4.yml
# python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/config5.yml

# python /home/nikoskot/earthnetThesis/swinUnet/hyperparameterOptimizeVideoSwinUnet.py --optimizeHyperparams

# python swinUnet/trainVideoSwinUnetV2.py --config /home/nikoskot/experiments/config.yml
# python swinUnet/trainVideoSwinUnet.py --config /home/nikoskot/earthnetThesis/experiments/config.yml --resumeTraining --resumeCheckpoint /home/nikoskot/earthnetThesis/experiments/videoSwinUnet_18-07-2024_16-57-37/checkpoint.pth
# python channelUnet/channelUnetReproduction.py --config /home/nikoskot/earthnetThesis/experiments/config.yml

# python swinUnet/testVideoSwinUnet.py --trainingFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnet_18-07-2024_16-57-37 --testSplit iid_test_split
# python swinUnet/testVideoSwinUnetV2.py --trainingFolder /home/nikoskot/experiments/videoSwinUNetV2_08-07-2024_20:45:11 --testSplit iid_test_split
# python channelUnet/testChannelUnet.py --trainingFolder /home/nikoskot/earthnetThesis/experiments/ChannelUnet_13-07-2024_17-59-15 --testSplit iid_test_split

# python swinUnet/ensScoreCalculation.py --predictionsFolder /home/nikoskot/earthnetThesis/experiments/ChannelUnet_13-07-2024_17-59-15/predictions/iid_test_split --targetsFolder /home/nikoskot/earthnetThesis/EarthnetDataset/iid_test_split/target --dataOutputFilePath /home/nikoskot/earthnetThesis/experiments/ChannelUnet_13-07-2024_17-59-15/data_output.json --scoreOutputFilePath /home/nikoskot/earthnetThesis/experiments/ChannelUnet_13-07-2024_17-59-15/score_output.json
