#!/bin/bash
#SBATCH --partition=A100short
#SBATCH --time=8:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --dependency=afterany:121971

python checkGPU.py

python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnetV2.py --config /home/nikoskot/earthnetThesis/experiments/configV2CosAn.yml --resumeTraining --resumeCheckpoint /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV2/videoSwinUnetV2_13-09-2024_10-49-40/checkpointLast.pth
