#!/bin/bash
#SBATCH --partition=A100short
#SBATCH --time=8:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --dependency=afterany:124079

python checkGPU.py

python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnetAll.py --config /home/nikoskot/earthnetThesis/experiments/configV3PretrainedSameLr.yml --resumeTraining --resumeCheckpoint /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV3/videoSwinUnetV3_16-10-2024_17-09-47/checkpointLast.pth

# python /home/nikoskot/earthnetThesis/swinUnet/testVideoSwinUnet.py --trainingFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_13-09-2024_10-31-50 --testSplit iid_test_split --checkpoint checkpointENS_20-09-2024_09-47-44.pth

# python /home/nikoskot/earthnetThesis/swinUnet/ensScoreCalculation.py --predictionsFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_13-09-2024_10-31-50/predictions/checkpointENS_20-09-2024_09-47-44.pth/iid_test_split --targetsFolder /home/nikoskot/earthnetThesis/EarthnetDataset/iid_test_split/target --dataOutputFilePath /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_13-09-2024_10-31-50/checkpointENS_20-09-2024_09-47-44data_output.json --scoreOutputFilePath /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV1/videoSwinUnetV1_13-09-2024_10-31-50/checkpointENS_20-09-2024_09-47-44score_output.json