#!/bin/bash
#SBATCH --partition=A100short
#SBATCH --time=8:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --dependency=afterany:124362

python checkGPU.py

# python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnetAll.py --config /home/nikoskot/earthnetThesis/experiments/configV7.yml --resumeTraining --resumeCheckpoint /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV7/videoSwinUnetV7_20-10-2024_14-06-14/checkpointLast.pth

python /home/nikoskot/earthnetThesis/swinUnet/testVideoSwinUnet.py --trainingFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV7/videoSwinUnetV7_20-10-2024_14-06-14 --testSplit iid_test_split --checkpoint checkpointENS_23-10-2024_06-08-53.pth

python /home/nikoskot/earthnetThesis/swinUnet/ensScoreCalculation.py --predictionsFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV7/videoSwinUnetV7_20-10-2024_14-06-14/predictions/checkpointENS_23-10-2024_06-08-53.pth/iid_test_split --targetsFolder /home/nikoskot/earthnetThesis/EarthnetDataset/iid_test_split/target --dataOutputFilePath /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV7/videoSwinUnetV7_20-10-2024_14-06-14/checkpointENS_23-10-2024_06-08-53data_output.json --scoreOutputFilePath /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV7/videoSwinUnetV7_20-10-2024_14-06-14/predictions/checkpointENS_23-10-2024_06-08-53score_output.json