#!/bin/bash
#SBATCH --partition=A100short
#SBATCH --time=8:00:00
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --dependency=afterany:124371

python checkGPU.py

# python /home/nikoskot/earthnetThesis/swinUnet/trainVideoSwinUnetAll.py --config /home/nikoskot/earthnetThesis/experiments/configV8DownUpSamplingLOAN.yml --resumeTraining --resumeCheckpoint /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV8/videoSwinUnetV8_20-10-2024_14-09-01/checkpointLast.pth

python /home/nikoskot/earthnetThesis/swinUnet/testVideoSwinUnet.py --trainingFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV8/videoSwinUnetV8_20-10-2024_14-09-01 --testSplit iid_test_split --checkpoint checkpointENS_23-10-2024_06-12-23.pth

python /home/nikoskot/earthnetThesis/swinUnet/ensScoreCalculation.py --predictionsFolder /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV8/videoSwinUnetV8_20-10-2024_14-09-01/predictions/checkpointENS_23-10-2024_06-12-23.pth/iid_test_split --targetsFolder /home/nikoskot/earthnetThesis/EarthnetDataset/iid_test_split/target --dataOutputFilePath /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV8/videoSwinUnetV8_20-10-2024_14-09-01/checkpointENS_23-10-2024_06-12-23data_output.json --scoreOutputFilePath /home/nikoskot/earthnetThesis/experiments/videoSwinUnetV8/videoSwinUnetV8_20-10-2024_14-09-01/checkpointENS_23-10-2024_06-12-23score_output.json