batchSize: 8
numWorkers: 8
trainDataDir: /hpcwork/nq011071/earthnetThesis/EarthnetDataset/train
testDataDir: /hpcwork/nq011071/earthnetThesis/EarthnetDataset
dataDtype: float32
trainDataSubset: null
trainSplit: 0.8
validationSplit: 0.2
cropMesodynamic: true
experimentsFolder: /hpcwork/nq011071/earthnetThesis/experimentsRwthHPC/videoSwinUnetV1/
overfitTraining: false
visualizationFreq: 10
calculateENSonValidationFreq: 10
modelType: videoSwinUnetV1
pretrained: null
pretrained2D: true
C: 96
modelInputCh: 11
extraInputCh: 5
mainInputTime: 10
outputTime: 20
modelOutputCh: 4
timeUpsampling: encoder
inputHeightWidth: 128
windowSize: [2, 7, 7]
patchSize: [1, 2, 2]
ape: true
patchEmbedding: {norm: BatchNorm}
encoder:
  numChannels: [96, 192]
  layerDepths: [2, 2]
  layerNumHeads: [3, 6, 12]
  mlpRatio: 4.0
  qkvBias: true
  qkScale: null
  drop: 0.0
  attnDrop: 0.0
  dropPath: 0.2
  norm: BatchNorm
  downsample: [false, true]
  downsampleNorm: BatchNorm
  useCheckpoint: false
decoder:
  numChannels: [192, 192]
  layerDepths: [2, 2]
  layerNumHeads: [3, 6, 12]
  mlpRatio: 4.0
  qkvBias: true
  qkScale: null
  drop: 0.0
  attnDrop: 0.0
  dropPath: 0.2
  norm: BatchNorm
  upsample: [true, false]
  upsampleNorm: BatchNorm
  useCheckpoint: false
epochs: 90
l1Weight: 1
mseWeight: 1
ssimWeight: 1
vggWeight: 1
trainingOptimizer: adamw
lr: 0.0002
weightDecay: 0.05
scheduler: CosineAnnealing
warmupEpochs: 5
lrScaleFactor: 0.2
schedulerPatience: 5
cosineAnnealingRestartsInterval: 10
gradientClipping: false
gradientClipValue: 0.5
useMSE: false
useSSIM: true
useVGG: false
runFolder: videoSwinUnetV1_07-10-2024_14-22-40
